const Map<String, String> stringsEn = {
  'app_name': 'Smart Finance',
  'nav_history': 'History',
  'nav_calendar': 'Calendar',
  'nav_stats': 'Statistics',
  'nav_map': 'Map',
  'nav_settings': 'Settings',
  'nav_categories': 'Categories',
  'balance': 'Balance',
  'income': 'Income',
  'expense': 'Expense',
  'recent_transactions': 'Recent transactions',
  'see_all': 'See all',
  'no_transactions': 'No transactions yet',
  'add_transaction': 'Add transaction',
  'edit_transaction': 'Edit transaction',
  'tx_name': 'Name',
  'tx_amount': 'Amount',
  'tx_category': 'Category',
  'tx_time': 'Time',
  'tx_note': 'Note',
  'tx_location': 'Location',
  'bank_balance_title': 'Account balance (from bank)',
  'bank_balance_waiting': 'Waiting for a bank notification with a balance',
  'bank_balance_estimated': 'estimated',
  'updated_at': 'updated {t}',
  'bank_original': 'Original notification',
  'copy': 'Copy',
  'copied': 'Copied',
  'bank_balance_after': 'Balance after: {n}',
  'server_status_off': 'No server connected — the app runs offline on this device.',
  'show': 'Show',
  'server_not_connected': 'No server connected',
  'auth_sign_in': 'Sign in',
  'auth_sign_up': 'Sign up',
  'auth_create': 'Create account',
  'auth_name': 'Display name',
  'auth_email': 'Email',
  'auth_password': 'Password',
  'auth_password_confirm': 'Confirm password',
  'auth_password_mismatch': 'Passwords do not match',
  'auth_forgot': 'Forgot password?',
  'auth_or': 'or',
  'auth_invalid_login': 'Wrong email or password',
  'auth_email_not_confirmed':
      'Email not confirmed — open your inbox and click the confirmation link',
  'auth_user_exists': 'This email already has an account — please sign in',
  'auth_weak_password': 'Password must be at least 6 characters',
  'auth_rate_limit': 'Too many attempts, please try again in a few minutes',
  'auth_bad_code': 'Code is wrong or expired',
  'auth_signup_disabled': 'New sign-ups are disabled on this server',
  'auth_bad_email': 'Invalid email',
  'auth_provider_disabled': 'This sign-in method is not enabled on the server',
  'auth_check_email': 'Account created. Open {e}, click the confirmation link, then sign in.',
  'auth_enter_email_first': 'Enter your email first',
  'auth_reset_title': 'Reset password',
  'auth_reset_sent':
      'Recovery email sent to {e}. Open it on this phone and tap the link — the app opens so you can set a new password. If the email has a code, enter it with a new password below.',
  'auth_new_password_title': 'Set a new password',
  'accounts': 'Accounts',
  'accounts_on_device': 'Accounts on this device',
  'account_other': 'Or sign in with another account',
  'account_add': 'Add account',
  'account_add_sub': 'Sign in with another Google/email account and keep this one',
  'account_switched': 'Switched to {n}',
  'account_forget': 'Remove from this device',
  'account_forget_confirm': 'Remove {n} from this device? Cloud data is kept.',
  'account_expired': 'This account\'s session has expired. Please sign in again.',
  'auth_code': 'Code from email',
  'auth_new_password': 'New password',
  'auth_password_changed': 'Password changed and signed in',
  'photo_view': 'View photo',
  'photo_download': 'Download',
  'photo_saved': 'Photo saved: {p}',
  'use_current_location': 'Use current location',
  'moments': 'Moments',
  'moments_empty':
      'No photos yet. Open a transaction and tap "Capture moment" to save a photo and where you spent.',
  'moment_title': 'Moment',
  'moment_caption_hint': 'Add a caption…',
  'moment_no_location': 'Location unavailable',
  'moment_retake': 'Retake',
  'moment_locating': 'Getting location…',
  'moment_capture': 'Capture moment',
  'moment_capture_sub': 'Square photo + location, saved on device and uploaded when online',
  'moment_pending_upload': 'Saved on device — will upload when online',
  'tx_latitude': 'Latitude',
  'tx_longitude': 'Longitude',
  'tx_photo': 'Receipt photo',
  'take_photo': 'Take photo',
  'choose_photo': 'Choose photo',
  'remove_photo': 'Remove photo',
  'pick_on_map': 'Pick on map',
  'photo_on_cloud': 'Photo stored in the cloud',
  'save': 'Save',
  'cancel': 'Cancel',
  'delete': 'Delete',
  'edit': 'Edit',
  'confirm': 'Confirm',
  'close': 'Close',
  'retry': 'Retry',
  'all': 'All',
  'optional': 'Optional',
  'delete_confirm_title': 'Delete this item?',
  'delete_confirm_msg': 'This will be synced to your other devices.',
  'saved': 'Saved',
  'deleted': 'Deleted',
  'validation_name': 'Please enter a name',
  'validation_amount': 'Amount must be greater than 0',
  'validation_coordinates': 'Invalid coordinates',
  'category_uncategorized': 'Uncategorized',
  'categories': 'Categories',
  'add_category': 'Add category',
  'edit_category': 'Edit category',
  'category_name': 'Category name',
  'category_icon': 'Icon',
  'category_color': 'Color',
  'cat_food': 'Food & drink',
  'cat_transport': 'Transport',
  'cat_shopping': 'Shopping',
  'cat_bills': 'Bills',
  'cat_entertainment': 'Entertainment',
  'cat_health': 'Health',
  'cat_education': 'Education',
  'cat_home': 'Home',
  'cat_other_expense': 'Other expense',
  'cat_salary': 'Salary',
  'cat_bonus': 'Bonus',
  'cat_investment': 'Investment',
  'cat_other_income': 'Other income',
  'history_title': 'Transaction history',
  'load_more_cloud': 'Load more from cloud',
  'archived_note': '{n} older transactions are archived in the cloud to save space.',
  'calendar_title': 'Expense calendar',
  'day_net': 'Day total',
  'no_tx_day': 'No transactions on this day',
  'stats_title': 'Statistics',
  'by_category': 'By category',
  'tx_count': '{n} transactions',
  'frequency': 'Frequency',
  'start_date': 'Start date',
  'end_date': 'End date',
  'active': 'Active',
  'map_title': 'Expense map',
  'map_unavailable':
      'Map is temporarily unavailable (needs Internet). Location data is still saved.',
  'map_tap_to_pick': 'Tap the map to choose a location',
  'map_area_title': 'In this area',
  'map_area_summary': '{n} transactions · spent {m}',
  'map_area_empty': 'No transactions in the visible area',
  'map_show_all': 'Show all',
  'map_no_coords': 'Place name only (no coordinates)',
  'map_style': 'Map type',
  'map_style_standard': 'Default',
  'map_style_terrain': 'Terrain',
  'map_style_satellite': 'Satellite',
  'map_my_location': 'My location',
  'map_location_unavailable': 'Could not get your location. Turn on GPS and allow location access.',
  'appearance': 'Appearance',
  'theme': 'Theme',
  'theme_system': 'System',
  'theme_light': 'Light',
  'theme_dark': 'Dark',
  'language': 'Language',
  'language_system': 'System',
  'reduce_effects': 'Reduce effects (low-end devices)',
  'currency': 'Currency',
  'currency_note': 'Display only, no exchange conversion.',
  'notifications': 'Notifications',
  'security': 'Security',
  'app_lock': 'Lock app with PIN',
  'set_pin': 'Set PIN',
  'enter_pin': 'Enter PIN',
  'confirm_pin': 'Confirm PIN',
  'pin_mismatch': 'PINs do not match',
  'pin_wrong': 'Wrong PIN',
  'pin_rule': 'PIN must be 4-8 digits',
  'unlock': 'Unlock',
  'sync_title': 'Sync',
  'sync_now': 'Sync now',
  'sync_status_idle': 'Synced',
  'sync_status_syncing': 'Syncing...',
  'sync_status_offline': 'Offline - data kept on this device',
  'sync_status_disabled': 'Offline mode (not signed in)',
  'sync_status_error': 'Sync error - will retry automatically',
  'pending_changes': '{n} changes waiting to upload',
  'last_sync': 'Last sync: {d}',
  'never': 'never',
  'storage_title': 'Local temporary storage',
  'storage_used': 'Using {n}',
  'local_records': '{n} full transactions on device',
  'archived_records': '{n} older transactions kept as summaries',
  'retention': 'Keep transaction details on device',
  'retention_all': 'Keep all',
  'retention_days': 'Last {n} days',
  'keep_local_photos': 'Keep original photos after cloud upload',
  'clean_now': 'Clean temporary storage now',
  'cleaned': 'Freed {n}',
  'export_json': 'Back up to JSON file',
  'export_csv': 'Export CSV (Excel)',
  'import_json': 'Restore from JSON file',
  'restore_cloud': 'Restore everything from cloud',
  'export_done': 'Saved: {p}',
  'import_done': 'Imported: {a} new, {u} updated, {s} skipped, {i} invalid',
  'account': 'Account',
  'sign_in_google': 'Sign in with Google',
  'sign_out': 'Sign out',
  'offline_mode': 'Using offline',
  'use_offline': 'Continue offline without signing in',
  'login_subtitle': 'Smart expense tracking - works offline and syncs between phone and computer.',
  'cloud_not_configured':
      'No sync server connected. The app runs offline — tap Sync server to connect.',
  'signing_in': 'Opening browser to sign in...',
  'sign_out_pending':
      '{n} changes are not synced yet. They stay on this device and will sync when you sign in again.',
  'error_validation': 'Invalid data, please check again.',
  'error_auth': 'Session expired or denied. Please sign in again.',
  'error_network': 'No network connection. Your data is saved on this device.',
  'error_database': 'Database error. Please try again.',
  'error_storage': 'Could not process the file/photo. Will retry later.',
  'error_sync': 'Sync not completed, will retry.',
  'error_provider': 'External service is failing.',
  'error_unexpected': 'An unexpected error occurred.',
  'version': 'Version {v}',
  'today': 'Today',
  'yesterday': 'Yesterday',
  'this_month': 'This month',
  'type': 'Type',
  'bank_title': 'Auto-record from bank notifications',
  'bank_subtitle':
      'Detects balance changes from any bank or e-wallet, reads the amount aloud and saves the transaction.',
  'bank_android_only': 'This feature is only available on Android phones.',
  'bank_permission_ok': 'Notification access granted',
  'bank_permission_missing': 'Notification access not granted',
  'bank_grant': 'Grant access',
  'bank_restricted_hint':
      'If the switch in Settings is greyed out (Android 13+ with APKs installed outside Play Store): open App info → ⋮ → "Allow restricted settings", then grant access again.',
  'bank_app_info': 'App info',
  'bank_enable': 'Enable auto-record',
  'bank_speak': 'Read aloud on balance changes',
  'bank_speak_expense': 'Also read expenses',
  'bank_speak_test': 'Test voice',
  'bank_speak_sample': 'Đã nhận năm trăm nghìn đồng, Vietcombank',
  'bank_battery': 'Allow background running',
  'bank_battery_hint':
      'Some phones (Xiaomi, Oppo, Vivo, Samsung) kill background apps. Disable battery optimization for Smart Finance so no notification is missed.',
  'bank_test_title': 'Test detection',
  'bank_test_sender': 'Title / sender',
  'bank_test_content': 'Paste notification text',
  'bank_test_run': 'Check',
  'bank_test_ok': 'Detected',
  'bank_test_no': 'Ignored: {reason}',
  'bank_balance': 'Balance: {n}',
  'bank_supported': 'Built-in banks & wallets',
  'bank_supported_more':
      'Other banks are still detected automatically from the bank name and notification content.',
  'bank_log': 'Recent notification log',
  'bank_log_empty': 'No money-related notifications yet.',
  'bank_log_clear': 'Clear log',
  'bank_trust_app': 'Trust this app',
  'bank_block_app': 'Block this app',
  'bank_trusted_apps': 'Trusted apps',
  'bank_blocked_apps': 'Blocked apps',
  'bank_ignored': 'Ignored',
  'bank_income_name': 'Money received',
  'bank_expense_name': 'Spending',
  'bank_auto_note': 'Auto-recorded from {bank} notification',
  'bank_imported': 'Recorded {n} transactions from bank notifications',
  'bank_privacy':
      'Notification content is processed on this device only. The app only reads bank and wallet notifications; Zalo, Messenger, social, shopping, OTP and ads are always ignored.',
  'bank_pending': '{n} transactions waiting to be saved',
  'bank_reason_ok': 'Valid',
  'bank_reason_duplicate': 'Duplicate of a previous notification',
  'bank_reason_otp': 'OTP code',
  'bank_reason_promotion': 'Promotion / ad',
  'bank_reason_failed': 'Failed transaction',
  'bank_reason_reminder': 'Payment reminder / statement',
  'bank_reason_security': 'Security / login',
  'bank_reason_internal_transfer': 'Internal wallet top-up/withdrawal',
  'bank_reason_unknown_app': 'Not a banking app',
  'bank_reason_sms_not_bank': 'SMS not from a bank',
  'bank_reason_weak_signature': 'Not enough transaction evidence',
  'bank_reason_no_amount': 'No amount found',
  'bank_reason_balance_only': 'Balance only',
  'bank_reason_unknown_direction': 'Unclear money in or out',
  'bank_reason_user_blocked': 'You blocked this app',
  'bank_reason_blocked_app': 'Chat / social app',
  'bank_reason_bad_amount': 'Invalid amount',
  'bank_reason_empty': 'Empty notification',
  'glass_blur_all': 'Frosted glass on every card (prettier, uses more battery)',
  'animated_background': 'Animated background',
  'menu': 'Menu',
  'main_sections': 'Main',
  'bank_section': 'Auto-record',
  'tab_home': 'Home',
  'greeting': 'Hello, {name} 👋',
  'greeting_you': 'there',
  'greeting_sub': 'Smart money management, every day.',
  'menu_features': 'Feature menu',
  'new_features': 'New features',
  'new_badge': 'NEW',
  'no_notifications': 'No alerts. Everything looks good!',
  'total_assets': 'Total assets',
  'hide_balance': 'Hide balance',
  'show_balance': 'Show balance',
  'today_income': '+{n} today',
  'income_total': 'Income',
  'expense_total': 'Expenses',
  'savings': 'Savings',
  'monitoring_on': 'Monitoring is on',
  'monitoring_off': 'Monitoring is off',
  'monitoring_on_sub': 'Reading balance notifications automatically',
  'monitoring_off_sub': 'The app will not announce incoming money',
  'today_overview': 'Today at a glance',
  'tx_count_label': 'Transactions',
  'net_flow': 'Net cash flow',
  'tx_detail_title': 'Transaction details',
  'delete_tx_confirm': 'Are you sure you want to delete this transaction?',
  'reset': 'Reset',
  'advanced_filter': 'Advanced filter',
  'search_tx': 'Search transactions...',
  'clear': 'Clear',
  'this_week': 'This week',
  'this_year': 'This year',
  'month_n': 'Month {n}',
  'no_tx_yet': 'No transactions yet',
  'no_tx_filter': 'No matching transactions',
  'no_tx_yet_sub': 'Start recording your income and expenses.',
  'specific_time': 'Specific time',
  'pick_day': 'Pick day',
  'pick_month': 'Pick month',
  'pick_year': 'Pick year',
  'clear_time_filter': 'Clear time filter',
  'amount_range': 'Amount',
  'under_100k': 'Under 100k',
  'under_500k': 'Under 500k',
  'over_1m': 'Over 1 million',
  'apply_filter': 'Apply filter',
  'days_n': '{n} days',
  'months_n': '{n} months',
  'years_n': '{n} year',
  'no_stats': 'No statistics yet',
  'no_stats_sub': 'Add transactions to start tracking your finances.',
  'cash_flow': 'Cash flow',
  'transactions': 'Transactions',
  'balance_trend': 'Balance trend',
  'need_more_data': 'More data is needed to draw the chart',
  'income_vs_expense': 'Income vs. expenses',
  'tx_habits': 'Spending habits',
  'peak_hour': 'Busiest hour',
  'peak_day': 'Busiest day',
  'avg_per_day': 'Average per day',
  'n_tx_short': '{n} tx',
  'income_trend': 'Income trend',
  'trend_empty': 'Not enough data to analyse the trend yet.',
  'trend_start': 'Start tracking income from this month.',
  'trend_up': 'Income this month is up {p}% from last month. Great job!',
  'trend_down': 'Income this month is down {p}% from last month. Keep going!',
  'trend_flat': 'Your income is steady compared with last month.',
  'user_default': 'Smart Finance user',
  'not_connected_google': 'Not signed in',
  'services_permissions': 'Services & permissions',
  'autostart': 'Auto-start',
  'restart_listener': 'Restart notification service',
  'restart_listener_done': 'Notification reader restarted',
  'tts_settings': 'System text-to-speech settings',
  'granted_permissions': 'Granted permissions',
  'perm_notification': 'Notification access',
  'perm_battery': 'Ignore battery optimisation',
  'granted': 'Granted',
  'not_granted': 'Not granted',
  'sound': 'Sound',
  'volume_boost': 'Volume boost',
  'volume_boost_sub': 'Louder announcements for noisy places',
  'voice': 'Voice',
  'voice_female': 'Female',
  'voice_male': 'Male',
  'chime': 'Chime',
  'chime_default': 'Default',
  'chime_ting': 'Ting Ting',
  'chime_none': 'Off',
  'speech_rate': 'Speech rate: {p}%',
  'speech_pitch': 'Pitch: {p}%',
  'data_backup': 'Data & backup',
  'auto_backup': 'Automatic backup (cloud sync)',
  'login_for_backup': 'Sign in (email or Google) to enable cloud backup.',
  'simulate': 'Simulate',
  'simulate_title': 'Simulate a transaction',
  'simulate_content': 'Message text',
  'simulate_run': 'Run simulation',
  'simulate_sample':
      'TK 1012345678 +150,000VND vao 12:30. SD 1,250,000VND. ND: Chuyen khoan tu NGUYEN VAN A',
  'delete_all': 'Delete all',
  'delete_all_confirm':
      'All transaction data will be permanently deleted (including in the cloud). Are you sure?',
  'deleted_n': 'Deleted {n} transactions',
  'developer': 'Developer: Uri Shaw',
  'about_desc': 'Built to make reading money notifications smart, fun and friendly.',
  'sign_out_confirm': 'Are you sure you want to sign out?',
};
