/// 简体中文
const Map<String, String> stringsZhHans = {
  'app_name': 'Smart Finance',
  'nav_history': '历史',
  'nav_calendar': '日历',
  'nav_stats': '统计',
  'nav_map': '地图',
  'nav_settings': '设置',
  'nav_categories': '分类',
  'balance': '余额',
  'income': '收入',
  'expense': '支出',
  'recent_transactions': '最近交易',
  'see_all': '查看全部',
  'no_transactions': '暂无交易',
  'add_transaction': '添加交易',
  'edit_transaction': '编辑交易',
  'tx_name': '名称',
  'tx_amount': '金额',
  'tx_category': '分类',
  'tx_time': '时间',
  'tx_note': '备注',
  'tx_location': '地点',
  'bank_balance_title': '账户余额（银行通知）',
  'bank_balance_waiting': '等待含余额的银行通知',
  'bank_balance_estimated': '估算',
  'updated_at': '更新于 {t}',
  'bank_original': '原始通知',
  'copy': '复制',
  'copied': '已复制',
  'bank_balance_after': '交易后余额：{n}',
  'server_status_off': '尚未连接服务器 — 应用仅在本机离线运行。',
  'show': '显示',
  'server_not_connected': '尚未连接服务器',
  'auth_sign_in': '登录',
  'auth_sign_up': '注册',
  'auth_create': '创建账户',
  'auth_name': '显示名称',
  'auth_email': '邮箱',
  'auth_password': '密码',
  'auth_password_confirm': '确认密码',
  'auth_password_mismatch': '两次输入的密码不一致',
  'auth_forgot': '忘记密码？',
  'auth_or': '或',
  'auth_invalid_login': '邮箱或密码错误',
  'auth_email_not_confirmed': '邮箱尚未验证 — 请打开邮件点击验证链接',
  'auth_user_exists': '该邮箱已注册 — 请直接登录',
  'auth_weak_password': '密码至少 6 位',
  'auth_rate_limit': '操作过于频繁，请几分钟后再试',
  'auth_bad_code': '验证码错误或已过期',
  'auth_signup_disabled': '服务器已关闭新用户注册',
  'auth_bad_email': '邮箱无效',
  'auth_provider_disabled': '服务器未启用此登录方式',
  'auth_check_email': '账户已创建。请打开 {e} 点击验证链接后再登录。',
  'auth_enter_email_first': '请先输入邮箱',
  'auth_reset_title': '重置密码',
  'auth_reset_sent': '已向 {e} 发送恢复邮件。请在本手机上打开邮件并点击链接，应用会打开以设置新密码。若邮件中有验证码，请在下方输入验证码和新密码。',
  'auth_new_password_title': '设置新密码',
  'accounts': '账户',
  'accounts_on_device': '此设备上的账户',
  'account_other': '或登录其他账户',
  'account_add': '添加账户',
  'account_add_sub': '登录另一个 Google/邮箱账户，同时保留此账户',
  'account_switched': '已切换到 {n}',
  'account_forget': '从此设备移除',
  'account_forget_confirm': '从此设备移除 {n}？云端数据将保留。',
  'account_expired': '此账户的登录已过期，请重新登录。',
  'auth_code': '邮件中的验证码',
  'auth_new_password': '新密码',
  'auth_password_changed': '密码已修改并已登录',
  'photo_view': '查看照片',
  'photo_download': '下载照片',
  'photo_saved': '照片已保存：{p}',
  'use_current_location': '使用当前位置',
  'moments': '瞬间',
  'moments_empty': '还没有照片。打开一笔交易并点击“拍下瞬间”，保存照片和消费地点。',
  'moment_title': '瞬间',
  'moment_caption_hint': '添加留言…',
  'moment_no_location': '无法获取位置',
  'moment_retake': '重拍',
  'moment_locating': '正在获取位置…',
  'moment_capture': '拍下瞬间',
  'moment_capture_sub': '方形照片 + 位置，先存本机，联网后自动上传',
  'moment_pending_upload': '已存本机 — 联网后上传',
  'tx_latitude': '纬度',
  'tx_longitude': '经度',
  'tx_photo': '票据照片',
  'take_photo': '拍照',
  'choose_photo': '选择照片',
  'remove_photo': '删除照片',
  'pick_on_map': '在地图上选择',
  'photo_on_cloud': '照片已存储在云端',
  'save': '保存',
  'cancel': '取消',
  'delete': '删除',
  'edit': '编辑',
  'confirm': '确认',
  'close': '关闭',
  'retry': '重试',
  'all': '全部',
  'optional': '可选',
  'delete_confirm_title': '删除此项？',
  'delete_confirm_msg': '此操作将同步到您的其他设备。',
  'saved': '已保存',
  'deleted': '已删除',
  'validation_name': '请输入名称',
  'validation_amount': '金额必须大于 0',
  'validation_coordinates': '坐标无效',
  'category_uncategorized': '未分类',
  'categories': '分类',
  'add_category': '添加分类',
  'edit_category': '编辑分类',
  'category_name': '分类名称',
  'category_icon': '图标',
  'category_color': '颜色',
  'cat_food': '餐饮',
  'cat_transport': '交通',
  'cat_shopping': '购物',
  'cat_bills': '账单',
  'cat_entertainment': '娱乐',
  'cat_health': '健康',
  'cat_education': '教育',
  'cat_home': '居家',
  'cat_other_expense': '其他支出',
  'cat_salary': '工资',
  'cat_bonus': '奖金',
  'cat_investment': '投资',
  'cat_other_income': '其他收入',
  'history_title': '交易历史',
  'load_more_cloud': '从云端加载更多',
  'archived_note': '{n} 笔较早的交易已归档到云端以节省空间。',
  'calendar_title': '支出日历',
  'day_net': '当日收支',
  'no_tx_day': '当天没有交易',
  'stats_title': '统计',
  'by_category': '按分类',
  'tx_count': '{n} 笔交易',
  'frequency': '频率',
  'start_date': '开始日期',
  'end_date': '结束日期',
  'active': '启用',
  'map_title': '支出地图',
  'map_unavailable': '地图暂不可用（需要网络）。位置数据仍会保存。',
  'map_tap_to_pick': '点击地图选择位置',
  'map_area_title': '此区域内',
  'map_area_summary': '{n} 笔交易 · 支出 {m}',
  'map_area_empty': '当前可见区域内没有交易',
  'map_show_all': '显示全部',
  'map_no_coords': '仅有地点名称（无坐标）',
  'map_style': '地图类型',
  'map_style_standard': '默认',
  'map_style_terrain': '地形',
  'map_style_satellite': '卫星',
  'map_my_location': '我的位置',
  'map_location_unavailable': '无法获取位置。请开启 GPS 并允许定位权限。',
  'appearance': '外观',
  'theme': '主题',
  'theme_system': '跟随系统',
  'theme_light': '浅色',
  'theme_dark': '深色',
  'language': '语言',
  'language_system': '跟随系统',
  'reduce_effects': '减少特效（低配设备）',
  'currency': '货币',
  'currency_note': '仅改变显示，不进行汇率换算。',
  'notifications': '通知',
  'security': '安全',
  'app_lock': '使用 PIN 锁定应用',
  'set_pin': '设置 PIN',
  'enter_pin': '输入 PIN',
  'confirm_pin': '再次输入 PIN',
  'pin_mismatch': 'PIN 不一致',
  'pin_wrong': 'PIN 错误',
  'pin_rule': 'PIN 为 4-8 位数字',
  'unlock': '解锁',
  'sync_title': '同步',
  'sync_now': '立即同步',
  'sync_status_idle': '已同步',
  'sync_status_syncing': '正在同步...',
  'sync_status_offline': '离线 - 数据暂存在本机',
  'sync_status_disabled': '离线模式（未登录云端）',
  'sync_status_error': '同步出错 - 将自动重试',
  'pending_changes': '{n} 项更改等待上传',
  'last_sync': '上次同步：{d}',
  'never': '从未',
  'storage_title': '本机临时存储',
  'storage_used': '已使用 {n}',
  'local_records': '本机有 {n} 笔完整交易',
  'archived_records': '{n} 笔旧交易仅保留摘要',
  'retention': '在本机保留交易详情',
  'retention_all': '全部保留',
  'retention_days': '最近 {n} 天',
  'keep_local_photos': '上传云端后保留原始照片',
  'clean_now': '立即清理临时存储',
  'cleaned': '已释放 {n}',
  'export_json': '备份为 JSON 文件',
  'export_csv': '导出 CSV（Excel）',
  'import_json': '从 JSON 文件恢复',
  'restore_cloud': '从云端恢复全部',
  'export_done': '已保存：{p}',
  'import_done': '导入：新增 {a}，更新 {u}，跳过 {s}，无效 {i}',
  'account': '账户',
  'sign_in_google': '使用 Google 登录',
  'sign_out': '退出登录',
  'offline_mode': '正在离线使用',
  'use_offline': '不登录，离线使用',
  'login_subtitle': '智能记账 - 无网络也能使用，并在手机和电脑之间同步。',
  'cloud_not_configured': '尚未配置 Supabase（config/env.json），应用将完全离线运行。',
  'signing_in': '正在打开浏览器登录...',
  'sign_out_pending': '还有 {n} 项更改未同步，数据会保留在本机，重新登录后同步。',
  'error_validation': '数据无效，请检查。',
  'error_auth': '登录已过期或被拒绝，请重新登录。',
  'error_network': '无网络连接，数据已保存在本机。',
  'error_database': '数据库错误，请重试。',
  'error_storage': '无法处理文件/照片，稍后将重试。',
  'error_sync': '同步未完成，将自动重试。',
  'error_provider': '外部服务出错。',
  'error_unexpected': '发生意外错误。',
  'version': '版本 {v}',
  'today': '今天',
  'yesterday': '昨天',
  'this_month': '本月',
  'type': '类型',
  'bank_title': '从银行通知自动记账',
  'bank_subtitle': '自动识别所有银行和电子钱包的余额变动，朗读金额并保存交易。',
  'bank_android_only': '此功能仅适用于 Android 手机。',
  'bank_permission_ok': '已授予通知读取权限',
  'bank_permission_missing': '尚未授予通知读取权限',
  'bank_grant': '授予权限',
  'bank_restricted_hint': '如果设置中的开关为灰色（Android 13+ 且非应用商店安装）：打开应用信息 → ⋮ →“允许受限设置”，然后重新授权。',
  'bank_app_info': '应用信息',
  'bank_enable': '开启自动记账',
  'bank_speak': '余额变动时朗读',
  'bank_speak_expense': '支出也朗读',
  'bank_speak_test': '试听语音',
  'bank_speak_sample': 'Đã nhận năm trăm nghìn đồng, Vietcombank',
  'bank_battery': '允许后台运行',
  'bank_battery_hint': '部分手机（小米、OPPO、vivo、三星）会关闭后台应用。请为 Smart Finance 关闭电池优化，以免漏掉通知。',
  'bank_test_title': '测试识别',
  'bank_test_sender': '标题 / 发送者',
  'bank_test_content': '粘贴通知内容',
  'bank_test_run': '检查',
  'bank_test_ok': '识别成功',
  'bank_test_no': '已忽略：{reason}',
  'bank_balance': '余额：{n}',
  'bank_supported': '内置支持的银行与钱包',
  'bank_supported_more': '其他银行也会根据银行名称和通知内容自动识别。',
  'bank_log': '最近通知记录',
  'bank_log_empty': '暂无与金额相关的通知。',
  'bank_log_clear': '清除记录',
  'bank_trust_app': '信任此应用',
  'bank_block_app': '屏蔽此应用',
  'bank_trusted_apps': '信任的应用',
  'bank_blocked_apps': '已屏蔽的应用',
  'bank_ignored': '已忽略',
  'bank_income_name': '收到款项',
  'bank_expense_name': '支出',
  'bank_auto_note': '由 {bank} 通知自动记录',
  'bank_imported': '已从银行通知记录 {n} 笔交易',
  'bank_privacy': '通知内容仅在本机处理。应用只读取银行和钱包通知；Zalo、Messenger、社交、购物、OTP 和广告一律忽略。',
  'bank_pending': '{n} 笔交易等待保存',
  'bank_reason_ok': '有效',
  'bank_reason_duplicate': '与之前的通知重复',
  'bank_reason_otp': 'OTP 验证码',
  'bank_reason_promotion': '促销 / 广告',
  'bank_reason_failed': '交易失败',
  'bank_reason_reminder': '还款提醒 / 账单',
  'bank_reason_security': '安全 / 登录',
  'bank_reason_internal_transfer': '钱包内部充值/提现',
  'bank_reason_unknown_app': '非银行应用',
  'bank_reason_sms_not_bank': '非银行短信',
  'bank_reason_weak_signature': '交易特征不足',
  'bank_reason_no_amount': '未找到金额',
  'bank_reason_balance_only': '仅有余额',
  'bank_reason_unknown_direction': '无法判断收入或支出',
  'bank_reason_user_blocked': '你已屏蔽此应用',
  'bank_reason_blocked_app': '聊天 / 社交应用',
  'bank_reason_bad_amount': '金额无效',
  'bank_reason_empty': '空通知',
  'glass_blur_all': '所有卡片使用毛玻璃（更美观，更耗电）',
  'animated_background': '动态背景',
  'menu': '菜单',
  'main_sections': '主要',
  'bank_section': '自动记账',
  'tab_home': '首页',
  'greeting': '你好，{name} 👋',
  'greeting_you': '朋友',
  'greeting_sub': '每天智能管理你的财务。',
  'menu_features': '功能菜单',
  'new_features': '新功能',
  'new_badge': '新',
  'no_notifications': '没有提醒，一切正常！',
  'total_assets': '总资产',
  'hide_balance': '隐藏余额',
  'show_balance': '显示余额',
  'today_income': '今日 +{n}',
  'income_total': '收入',
  'expense_total': '支出',
  'savings': '结余',
  'monitoring_on': '监控已开启',
  'monitoring_off': '监控已关闭',
  'monitoring_on_sub': '正在自动播报余额变动',
  'monitoring_off_sub': '到账时应用不会播报',
  'today_overview': '今日概览',
  'tx_count_label': '交易笔数',
  'net_flow': '净现金流',
  'tx_detail_title': '交易详情',
  'delete_tx_confirm': '确定要删除这笔交易吗？',
  'reset': '重置',
  'advanced_filter': '高级筛选',
  'search_tx': '搜索交易...',
  'clear': '清除',
  'this_week': '本周',
  'this_year': '今年',
  'month_n': '{n}月',
  'no_tx_yet': '还没有交易',
  'no_tx_filter': '没有符合条件的交易',
  'no_tx_yet_sub': '开始记录你的收入和支出吧。',
  'specific_time': '具体时间',
  'pick_day': '选择日期',
  'pick_month': '选择月份',
  'pick_year': '选择年份',
  'clear_time_filter': '清除时间筛选',
  'amount_range': '金额',
  'under_100k': '10万以下',
  'under_500k': '50万以下',
  'over_1m': '100万以上',
  'apply_filter': '应用筛选',
  'days_n': '{n}天',
  'months_n': '{n}个月',
  'years_n': '{n}年',
  'no_stats': '暂无统计数据',
  'no_stats_sub': '添加交易后即可开始追踪财务。',
  'cash_flow': '现金流',
  'transactions': '交易',
  'balance_trend': '余额走势',
  'need_more_data': '需要更多数据才能显示图表',
  'income_vs_expense': '收支对比',
  'tx_habits': '交易习惯',
  'peak_hour': '最活跃时段',
  'peak_day': '最活跃日期',
  'avg_per_day': '日均',
  'n_tx_short': '{n} 笔',
  'income_trend': '收入趋势',
  'trend_empty': '暂无足够数据分析趋势。',
  'trend_start': '从本月开始追踪收入。',
  'trend_up': '本月收入比上月增长 {p}%，太棒了！',
  'trend_down': '本月收入比上月下降 {p}%，继续加油！',
  'trend_flat': '你的收入与上月持平。',
  'user_default': 'Smart Finance 用户',
  'not_connected_google': '未连接 Google',
  'services_permissions': '服务与权限',
  'autostart': '自启动',
  'restart_listener': '重启通知服务',
  'restart_listener_done': '已重启通知读取服务',
  'tts_settings': '系统语音设置',
  'granted_permissions': '已授予的权限',
  'perm_notification': '通知访问权限',
  'perm_battery': '忽略电池优化',
  'granted': '已授予',
  'not_granted': '未授予',
  'sound': '声音',
  'volume_boost': '音量增强',
  'volume_boost_sub': '在嘈杂环境中提高播报音量',
  'voice': '语音',
  'voice_female': '女声',
  'voice_male': '男声',
  'chime': '提示音',
  'chime_default': '默认',
  'chime_ting': '叮叮',
  'chime_none': '关闭',
  'speech_rate': '语速：{p}%',
  'speech_pitch': '音调：{p}%',
  'data_backup': '数据与备份',
  'auto_backup': '自动备份（云同步）',
  'login_for_backup': '使用 Google 登录以启用云备份。',
  'simulate': '模拟',
  'simulate_title': '模拟交易',
  'simulate_content': '短信内容',
  'simulate_run': '运行模拟',
  'simulate_sample':
      'TK 1012345678 +150,000VND vao 12:30. SD 1,250,000VND. ND: Chuyen khoan tu NGUYEN VAN A',
  'delete_all': '全部删除',
  'delete_all_confirm': '所有交易数据将被永久删除（包括云端）。确定吗？',
  'deleted_n': '已删除 {n} 笔交易',
  'developer': '开发者：Uri Shaw',
  'about_desc': '致力于让到账通知的播报更智能、更有趣、更友好。',
  'sign_out_confirm': '确定要退出登录吗？',
};

/// 繁體中文 - 以簡體為基礎，覆寫需要不同字形的詞條。
final Map<String, String> stringsZhHant = {
  ...stringsZhHans,
  'nav_history': '歷史',
  'nav_calendar': '日曆',
  'nav_stats': '統計',
  'nav_map': '地圖',
  'nav_settings': '設定',
  'nav_categories': '分類',
  'balance': '餘額',
  'expense': '支出',
  'recent_transactions': '最近交易',
  'see_all': '查看全部',
  'no_transactions': '暫無交易',
  'add_transaction': '新增交易',
  'edit_transaction': '編輯交易',
  'tx_name': '名稱',
  'tx_amount': '金額',
  'tx_category': '分類',
  'tx_note': '備註',
  'tx_location': '地點',
  'bank_balance_title': '帳戶餘額（銀行通知）',
  'bank_balance_waiting': '等待含餘額的銀行通知',
  'bank_balance_estimated': '估算',
  'updated_at': '更新於 {t}',
  'bank_original': '原始通知',
  'copy': '複製',
  'copied': '已複製',
  'bank_balance_after': '交易後餘額：{n}',
  'server_status_off': '尚未連線伺服器 — 應用僅在本機離線執行。',
  'show': '顯示',
  'server_not_connected': '尚未連線伺服器',
  'auth_sign_in': '登入',
  'auth_sign_up': '註冊',
  'auth_create': '建立帳戶',
  'auth_name': '顯示名稱',
  'auth_email': '電子郵件',
  'auth_password': '密碼',
  'auth_password_confirm': '確認密碼',
  'auth_password_mismatch': '兩次輸入的密碼不一致',
  'auth_forgot': '忘記密碼？',
  'auth_invalid_login': '電子郵件或密碼錯誤',
  'auth_email_not_confirmed': '電子郵件尚未驗證 — 請開啟郵件點擊驗證連結',
  'auth_user_exists': '此電子郵件已註冊 — 請直接登入',
  'auth_rate_limit': '操作過於頻繁，請幾分鐘後再試',
  'auth_bad_code': '驗證碼錯誤或已過期',
  'auth_signup_disabled': '伺服器已關閉新使用者註冊',
  'auth_bad_email': '電子郵件無效',
  'auth_provider_disabled': '伺服器未啟用此登入方式',
  'auth_check_email': '帳戶已建立。請開啟 {e} 點擊驗證連結後再登入。',
  'auth_enter_email_first': '請先輸入電子郵件',
  'auth_reset_title': '重設密碼',
  'auth_reset_sent': '已向 {e} 寄送恢復郵件。請在本手機上開啟郵件並點擊連結，應用程式會開啟以設定新密碼。若郵件中有驗證碼，請在下方輸入驗證碼和新密碼。',
  'auth_new_password_title': '設定新密碼',
  'accounts': '帳戶',
  'accounts_on_device': '此裝置上的帳戶',
  'account_other': '或登入其他帳戶',
  'account_add': '新增帳戶',
  'account_add_sub': '登入另一個 Google/電子郵件帳戶，同時保留此帳戶',
  'account_switched': '已切換到 {n}',
  'account_forget': '從此裝置移除',
  'account_forget_confirm': '從此裝置移除 {n}？雲端資料將保留。',
  'account_expired': '此帳戶的登入已過期，請重新登入。',
  'auth_code': '郵件中的驗證碼',
  'auth_new_password': '新密碼',
  'auth_password_changed': '密碼已變更並已登入',
  'photo_view': '查看照片',
  'photo_download': '下載照片',
  'photo_saved': '照片已儲存：{p}',
  'use_current_location': '使用目前位置',
  'moments': '瞬間',
  'moments_empty': '還沒有照片。打開一筆交易並點擊「拍下瞬間」，保存照片和消費地點。',
  'moment_title': '瞬間',
  'moment_caption_hint': '新增留言…',
  'moment_no_location': '無法取得位置',
  'moment_retake': '重拍',
  'moment_locating': '正在取得位置…',
  'moment_capture': '拍下瞬間',
  'moment_capture_sub': '方形照片 + 位置，先存本機，連網後自動上傳',
  'moment_pending_upload': '已存本機 — 連網後上傳',
  'tx_latitude': '緯度',
  'tx_longitude': '經度',
  'tx_photo': '收據照片',
  'take_photo': '拍照',
  'choose_photo': '選擇照片',
  'remove_photo': '刪除照片',
  'pick_on_map': '在地圖上選擇',
  'photo_on_cloud': '照片已儲存在雲端',
  'save': '儲存',
  'delete': '刪除',
  'edit': '編輯',
  'confirm': '確認',
  'close': '關閉',
  'retry': '重試',
  'optional': '可選',
  'delete_confirm_title': '刪除此項？',
  'delete_confirm_msg': '此操作將同步到您的其他裝置。',
  'saved': '已儲存',
  'deleted': '已刪除',
  'validation_name': '請輸入名稱',
  'validation_amount': '金額必須大於 0',
  'validation_coordinates': '座標無效',
  'category_uncategorized': '未分類',
  'add_category': '新增分類',
  'edit_category': '編輯分類',
  'category_name': '分類名稱',
  'category_icon': '圖示',
  'category_color': '顏色',
  'cat_food': '餐飲',
  'cat_transport': '交通',
  'cat_shopping': '購物',
  'cat_bills': '帳單',
  'cat_entertainment': '娛樂',
  'cat_health': '健康',
  'cat_education': '教育',
  'cat_home': '居家',
  'cat_other_expense': '其他支出',
  'cat_salary': '薪資',
  'cat_bonus': '獎金',
  'cat_investment': '投資',
  'cat_other_income': '其他收入',
  'history_title': '交易歷史',
  'load_more_cloud': '從雲端載入更多',
  'archived_note': '{n} 筆較早的交易已封存到雲端以節省空間。',
  'calendar_title': '支出日曆',
  'day_net': '當日收支',
  'no_tx_day': '當天沒有交易',
  'stats_title': '統計',
  'by_category': '依分類',
  'tx_count': '{n} 筆交易',
  'frequency': '頻率',
  'start_date': '開始日期',
  'end_date': '結束日期',
  'active': '啟用',
  'map_title': '支出地圖',
  'map_unavailable': '地圖暫時無法使用（需要網路）。位置資料仍會儲存。',
  'map_tap_to_pick': '點擊地圖選擇位置',
  'map_area_title': '此區域內',
  'map_area_summary': '{n} 筆交易 · 支出 {m}',
  'map_area_empty': '目前可見區域內沒有交易',
  'map_show_all': '顯示全部',
  'map_no_coords': '僅有地點名稱（無座標）',
  'map_style': '地圖類型',
  'map_style_standard': '預設',
  'map_style_terrain': '地形',
  'map_style_satellite': '衛星',
  'map_my_location': '我的位置',
  'map_location_unavailable': '無法取得位置。請開啟 GPS 並允許定位權限。',
  'appearance': '外觀',
  'theme': '主題',
  'theme_system': '跟隨系統',
  'theme_light': '淺色',
  'theme_dark': '深色',
  'language': '語言',
  'language_system': '跟隨系統',
  'reduce_effects': '減少特效（低階裝置）',
  'currency': '貨幣',
  'currency_note': '僅改變顯示，不進行匯率換算。',
  'notifications': '通知',
  'security': '安全性',
  'app_lock': '使用 PIN 鎖定應用程式',
  'set_pin': '設定 PIN',
  'enter_pin': '輸入 PIN',
  'confirm_pin': '再次輸入 PIN',
  'pin_mismatch': 'PIN 不一致',
  'pin_wrong': 'PIN 錯誤',
  'pin_rule': 'PIN 為 4-8 位數字',
  'unlock': '解鎖',
  'sync_title': '同步',
  'sync_now': '立即同步',
  'sync_status_idle': '已同步',
  'sync_status_syncing': '正在同步...',
  'sync_status_offline': '離線 - 資料暫存在本機',
  'sync_status_disabled': '離線模式（未登入雲端）',
  'sync_status_error': '同步出錯 - 將自動重試',
  'pending_changes': '{n} 項變更等待上傳',
  'last_sync': '上次同步：{d}',
  'never': '從未',
  'storage_title': '本機暫存空間',
  'storage_used': '已使用 {n}',
  'local_records': '本機有 {n} 筆完整交易',
  'archived_records': '{n} 筆舊交易僅保留摘要',
  'retention': '在本機保留交易詳情',
  'retention_all': '全部保留',
  'retention_days': '最近 {n} 天',
  'keep_local_photos': '上傳雲端後保留原始照片',
  'clean_now': '立即清理暫存空間',
  'cleaned': '已釋放 {n}',
  'export_json': '備份為 JSON 檔案',
  'export_csv': '匯出 CSV（Excel）',
  'import_json': '從 JSON 檔案還原',
  'restore_cloud': '從雲端還原全部',
  'export_done': '已儲存：{p}',
  'import_done': '匯入：新增 {a}，更新 {u}，略過 {s}，無效 {i}',
  'account': '帳戶',
  'sign_in_google': '使用 Google 登入',
  'sign_out': '登出',
  'offline_mode': '正在離線使用',
  'use_offline': '不登入，離線使用',
  'login_subtitle': '智慧記帳 - 無網路也能使用，並在手機與電腦之間同步。',
  'cloud_not_configured': '尚未設定 Supabase（config/env.json），應用程式將完全離線執行。',
  'signing_in': '正在開啟瀏覽器登入...',
  'sign_out_pending': '還有 {n} 項變更未同步，資料會保留在本機，重新登入後同步。',
  'error_validation': '資料無效，請檢查。',
  'error_auth': '登入已過期或被拒絕，請重新登入。',
  'error_network': '無網路連線，資料已儲存在本機。',
  'error_database': '資料庫錯誤，請重試。',
  'error_storage': '無法處理檔案/照片，稍後將重試。',
  'error_sync': '同步未完成，將自動重試。',
  'error_provider': '外部服務出錯。',
  'error_unexpected': '發生意外錯誤。',
  'version': '版本 {v}',
  'this_month': '本月',
  'type': '類型',
  'bank_title': '從銀行通知自動記帳',
  'bank_enable': '開啟自動記帳',
  'bank_speak': '餘額變動時朗讀',
  'bank_grant': '授予權限',
  'bank_log': '最近通知紀錄',
  'bank_ignored': '已忽略',
  'bank_income_name': '收到款項',
  'animated_background': '動態背景',
  'menu': '選單',
  'main_sections': '主要',
  'bank_section': '自動記帳',
  'tab_home': '首頁',
  'greeting': '你好，{name} 👋',
  'greeting_sub': '每天智慧管理你的財務。',
  'menu_features': '功能選單',
  'new_features': '新功能',
  'no_notifications': '沒有提醒，一切正常！',
  'total_assets': '總資產',
  'hide_balance': '隱藏餘額',
  'show_balance': '顯示餘額',
  'today_income': '今日 +{n}',
  'income_total': '收入',
  'expense_total': '支出',
  'savings': '結餘',
  'monitoring_on': '監控已開啟',
  'monitoring_off': '監控已關閉',
  'monitoring_on_sub': '正在自動播報餘額變動',
  'monitoring_off_sub': '到帳時應用不會播報',
  'today_overview': '今日概覽',
  'tx_count_label': '交易筆數',
  'net_flow': '淨現金流',
  'tx_detail_title': '交易詳情',
  'delete_tx_confirm': '確定要刪除這筆交易嗎？',
  'reset': '重設',
  'advanced_filter': '進階篩選',
  'search_tx': '搜尋交易...',
  'clear': '清除',
  'this_week': '本週',
  'this_year': '今年',
  'no_tx_yet': '還沒有交易',
  'no_tx_filter': '沒有符合條件的交易',
  'no_tx_yet_sub': '開始記錄你的收入和支出吧。',
  'specific_time': '具體時間',
  'pick_day': '選擇日期',
  'pick_month': '選擇月份',
  'pick_year': '選擇年份',
  'clear_time_filter': '清除時間篩選',
  'amount_range': '金額',
  'under_100k': '10萬以下',
  'under_500k': '50萬以下',
  'over_1m': '100萬以上',
  'apply_filter': '套用篩選',
  'days_n': '{n}天',
  'months_n': '{n}個月',
  'no_stats': '暫無統計資料',
  'no_stats_sub': '新增交易後即可開始追蹤財務。',
  'cash_flow': '現金流',
  'transactions': '交易',
  'balance_trend': '餘額走勢',
  'need_more_data': '需要更多資料才能顯示圖表',
  'income_vs_expense': '收支對比',
  'tx_habits': '交易習慣',
  'peak_hour': '最活躍時段',
  'peak_day': '最活躍日期',
  'avg_per_day': '日均',
  'n_tx_short': '{n} 筆',
  'income_trend': '收入趨勢',
  'trend_empty': '暫無足夠資料分析趨勢。',
  'trend_start': '從本月開始追蹤收入。',
  'trend_up': '本月收入比上月增長 {p}%，太棒了！',
  'trend_down': '本月收入比上月下降 {p}%，繼續加油！',
  'trend_flat': '你的收入與上月持平。',
  'user_default': 'Smart Finance 使用者',
  'not_connected_google': '未連接 Google',
  'services_permissions': '服務與權限',
  'autostart': '自動啟動',
  'restart_listener': '重新啟動通知服務',
  'restart_listener_done': '已重新啟動通知讀取服務',
  'tts_settings': '系統語音設定',
  'granted_permissions': '已授予的權限',
  'perm_notification': '通知存取權限',
  'perm_battery': '忽略電池最佳化',
  'granted': '已授予',
  'not_granted': '未授予',
  'sound': '聲音',
  'volume_boost': '音量增強',
  'volume_boost_sub': '在吵雜環境中提高播報音量',
  'voice': '語音',
  'voice_female': '女聲',
  'voice_male': '男聲',
  'chime': '提示音',
  'chime_default': '預設',
  'chime_ting': '叮叮',
  'chime_none': '關閉',
  'speech_rate': '語速：{p}%',
  'speech_pitch': '音調：{p}%',
  'data_backup': '資料與備份',
  'auto_backup': '自動備份（雲端同步）',
  'login_for_backup': '使用 Google 登入以啟用雲端備份。',
  'simulate': '模擬',
  'simulate_title': '模擬交易',
  'simulate_content': '簡訊內容',
  'simulate_run': '執行模擬',
  'delete_all': '全部刪除',
  'delete_all_confirm': '所有交易資料將被永久刪除（包括雲端）。確定嗎？',
  'deleted_n': '已刪除 {n} 筆交易',
  'developer': '開發者：Uri Shaw',
  'about_desc': '致力於讓到帳通知的播報更智慧、更有趣、更友善。',
  'sign_out_confirm': '確定要登出嗎？',
  'tx_time': '時間',
};
