const Map<String, String> stringsVi = {
  'app_name': 'Smart Finance',
  'nav_history': 'Lịch sử',
  'nav_calendar': 'Lịch',
  'nav_stats': 'Thống kê',
  'nav_map': 'Bản đồ',
  'nav_settings': 'Cài đặt',
  'nav_categories': 'Danh mục',
  'balance': 'Số dư',
  'income': 'Thu',
  'expense': 'Chi',
  'recent_transactions': 'Giao dịch gần đây',
  'see_all': 'Xem tất cả',
  'no_transactions': 'Chưa có giao dịch nào',
  'add_transaction': 'Thêm giao dịch',
  'edit_transaction': 'Sửa giao dịch',
  'tx_name': 'Tên giao dịch',
  'tx_amount': 'Số tiền',
  'tx_category': 'Danh mục',
  'tx_time': 'Giờ',
  'tx_note': 'Ghi chú',
  'tx_location': 'Địa điểm',
  'bank_balance_title': 'Số dư tài khoản (theo ngân hàng)',
  'bank_balance_waiting': 'Chờ thông báo ngân hàng có ghi số dư',
  'bank_balance_estimated': 'ước tính',
  'updated_at': 'cập nhật {t}',
  'bank_original': 'Thông báo gốc',
  'copy': 'Sao chép',
  'copied': 'Đã sao chép',
  'bank_balance_after': 'Số dư sau GD: {n}',
  'server_status_off': 'Chưa kết nối máy chủ — app đang chạy offline trên máy này.',
  'show': 'Hiện',
  'server_not_connected': 'Chưa kết nối máy chủ',
  'auth_sign_in': 'Đăng nhập',
  'auth_sign_up': 'Đăng ký',
  'auth_create': 'Tạo tài khoản',
  'auth_name': 'Tên hiển thị',
  'auth_email': 'Email',
  'auth_password': 'Mật khẩu',
  'auth_password_confirm': 'Nhập lại mật khẩu',
  'auth_password_mismatch': 'Mật khẩu nhập lại không khớp',
  'auth_forgot': 'Quên mật khẩu?',
  'auth_or': 'hoặc',
  'auth_invalid_login': 'Sai email hoặc mật khẩu',
  'auth_email_not_confirmed': 'Email chưa được xác nhận — mở hộp thư và bấm link xác nhận',
  'auth_user_exists': 'Email này đã có tài khoản — hãy đăng nhập',
  'auth_weak_password': 'Mật khẩu tối thiểu 6 ký tự',
  'auth_rate_limit': 'Thao tác quá nhiều lần, vui lòng thử lại sau ít phút',
  'auth_bad_code': 'Mã không đúng hoặc đã hết hạn',
  'auth_signup_disabled': 'Máy chủ đang tắt đăng ký tài khoản mới',
  'auth_bad_email': 'Email không hợp lệ',
  'auth_provider_disabled': 'Cách đăng nhập này chưa được bật trên máy chủ',
  'auth_check_email': 'Đã tạo tài khoản. Mở email {e} và bấm link xác nhận rồi đăng nhập.',
  'auth_enter_email_first': 'Nhập email của bạn trước',
  'auth_reset_title': 'Đặt lại mật khẩu',
  'auth_reset_sent':
      'Đã gửi email khôi phục tới {e}. Mở email trên điện thoại này và bấm link — app sẽ mở để bạn đặt mật khẩu mới. Nếu email có mã số, nhập mã và mật khẩu mới bên dưới.',
  'auth_new_password_title': 'Đặt mật khẩu mới',
  'accounts': 'Tài khoản',
  'accounts_on_device': 'Tài khoản trên máy này',
  'account_other': 'Hoặc đăng nhập tài khoản khác',
  'account_add': 'Thêm tài khoản',
  'account_add_sub': 'Đăng nhập thêm tài khoản Google/email, vẫn giữ tài khoản này',
  'account_switched': 'Đã chuyển sang {n}',
  'account_forget': 'Bỏ khỏi máy này',
  'account_forget_confirm':
      'Bỏ {n} khỏi danh sách trên máy này? Dữ liệu trên cloud vẫn giữ nguyên.',
  'account_expired': 'Phiên đăng nhập của tài khoản này đã hết hạn. Hãy đăng nhập lại.',
  'auth_code': 'Mã trong email',
  'auth_new_password': 'Mật khẩu mới',
  'auth_password_changed': 'Đã đổi mật khẩu và đăng nhập',
  'photo_view': 'Xem ảnh',
  'photo_download': 'Tải ảnh về',
  'photo_saved': 'Đã lưu ảnh: {p}',
  'use_current_location': 'Lấy vị trí hiện tại',
  'moments': 'Khoảnh khắc',
  'moments_empty':
      'Chưa có ảnh nào. Mở một giao dịch và chạm "Chụp khoảnh khắc" để lưu lại ảnh và nơi bạn chi tiêu.',
  'moment_title': 'Khoảnh khắc',
  'moment_caption_hint': 'Thêm lời nhắn…',
  'moment_no_location': 'Không lấy được vị trí',
  'moment_retake': 'Chụp lại',
  'moment_locating': 'Đang lấy vị trí…',
  'moment_capture': 'Chụp khoảnh khắc',
  'moment_capture_sub': 'Ảnh vuông + vị trí, lưu trên máy và tự đẩy lên khi có mạng',
  'moment_pending_upload': 'Đã lưu trên máy — sẽ tải lên khi có mạng',
  'tx_latitude': 'Vĩ độ',
  'tx_longitude': 'Kinh độ',
  'tx_photo': 'Ảnh hóa đơn',
  'take_photo': 'Chụp ảnh',
  'choose_photo': 'Chọn ảnh',
  'remove_photo': 'Xóa ảnh',
  'pick_on_map': 'Chọn trên bản đồ',
  'photo_on_cloud': 'Ảnh đã lưu trên cloud',
  'save': 'Lưu',
  'cancel': 'Hủy',
  'delete': 'Xóa',
  'edit': 'Sửa',
  'confirm': 'Xác nhận',
  'close': 'Đóng',
  'retry': 'Thử lại',
  'all': 'Tất cả',
  'optional': 'Không bắt buộc',
  'delete_confirm_title': 'Xóa mục này?',
  'delete_confirm_msg': 'Thao tác này sẽ được đồng bộ sang các thiết bị khác.',
  'saved': 'Đã lưu',
  'deleted': 'Đã xóa',
  'validation_name': 'Vui lòng nhập tên',
  'validation_amount': 'Số tiền phải lớn hơn 0',
  'validation_coordinates': 'Tọa độ không hợp lệ',
  'category_uncategorized': 'Chưa phân loại',
  'categories': 'Danh mục',
  'add_category': 'Thêm danh mục',
  'edit_category': 'Sửa danh mục',
  'category_name': 'Tên danh mục',
  'category_icon': 'Biểu tượng',
  'category_color': 'Màu',
  'cat_food': 'Ăn uống',
  'cat_transport': 'Di chuyển',
  'cat_shopping': 'Mua sắm',
  'cat_bills': 'Hóa đơn',
  'cat_entertainment': 'Giải trí',
  'cat_health': 'Sức khỏe',
  'cat_education': 'Giáo dục',
  'cat_home': 'Nhà cửa',
  'cat_other_expense': 'Chi khác',
  'cat_salary': 'Lương',
  'cat_bonus': 'Thưởng',
  'cat_investment': 'Đầu tư',
  'cat_other_income': 'Thu khác',
  'history_title': 'Lịch sử giao dịch',
  'load_more_cloud': 'Tải thêm từ cloud',
  'archived_note': '{n} giao dịch cũ đã được lưu trữ trên cloud để tiết kiệm bộ nhớ.',
  'calendar_title': 'Lịch chi tiêu',
  'day_net': 'Cả ngày',
  'no_tx_day': 'Không có giao dịch trong ngày này',
  'stats_title': 'Thống kê',
  'by_category': 'Theo danh mục',
  'tx_count': '{n} giao dịch',
  'frequency': 'Tần suất',
  'start_date': 'Ngày bắt đầu',
  'end_date': 'Ngày kết thúc',
  'active': 'Đang bật',
  'map_title': 'Bản đồ chi tiêu',
  'map_unavailable': 'Bản đồ tạm thời không khả dụng (cần Internet). Dữ liệu vị trí vẫn được lưu.',
  'map_tap_to_pick': 'Chạm vào bản đồ để chọn vị trí',
  'map_area_title': 'Trong khu vực này',
  'map_area_summary': '{n} giao dịch · chi {m}',
  'map_area_empty': 'Không có giao dịch nào trong vùng đang xem',
  'map_show_all': 'Xem tất cả',
  'map_no_coords': 'Chỉ có tên địa điểm (chưa có toạ độ)',
  'map_my_location': 'Vị trí của tôi',
  'map_location_unavailable': 'Không lấy được vị trí. Hãy bật GPS và cho phép quyền vị trí.',
  'appearance': 'Giao diện',
  'theme': 'Chủ đề',
  'theme_system': 'Theo hệ thống',
  'theme_light': 'Sáng',
  'theme_dark': 'Tối',
  'language': 'Ngôn ngữ',
  'language_system': 'Theo hệ thống',
  'reduce_effects': 'Giảm hiệu ứng (máy yếu)',
  'currency': 'Tiền tệ',
  'currency_note': 'Chỉ đổi cách hiển thị, không quy đổi tỷ giá.',
  'notifications': 'Thông báo',
  'security': 'Bảo mật',
  'app_lock': 'Khóa ứng dụng bằng mã PIN',
  'set_pin': 'Đặt mã PIN',
  'enter_pin': 'Nhập mã PIN',
  'confirm_pin': 'Nhập lại mã PIN',
  'pin_mismatch': 'Mã PIN không khớp',
  'pin_wrong': 'Sai mã PIN',
  'pin_rule': 'PIN gồm 4-8 chữ số',
  'unlock': 'Mở khóa',
  'sync_title': 'Đồng bộ',
  'sync_now': 'Đồng bộ ngay',
  'sync_status_idle': 'Đã đồng bộ',
  'sync_status_syncing': 'Đang đồng bộ...',
  'sync_status_offline': 'Offline - dữ liệu lưu tạm trên máy',
  'sync_status_disabled': 'Chế độ offline (chưa đăng nhập cloud)',
  'sync_status_error': 'Lỗi đồng bộ - sẽ tự thử lại',
  'pending_changes': '{n} thay đổi đang chờ đẩy lên cloud',
  'last_sync': 'Lần đồng bộ cuối: {d}',
  'never': 'chưa có',
  'storage_title': 'Bộ nhớ tạm trên máy',
  'storage_used': 'Đang dùng {n}',
  'local_records': '{n} giao dịch đầy đủ trên máy',
  'archived_records': '{n} giao dịch cũ chỉ lưu bản rút gọn',
  'retention': 'Giữ chi tiết giao dịch trên máy',
  'retention_all': 'Giữ tất cả',
  'retention_days': '{n} ngày gần nhất',
  'keep_local_photos': 'Giữ ảnh gốc trên máy sau khi đã lên cloud',
  'clean_now': 'Dọn bộ nhớ tạm ngay',
  'cleaned': 'Đã dọn {n}',
  'export_json': 'Sao lưu ra file JSON',
  'export_csv': 'Xuất CSV (Excel)',
  'import_json': 'Khôi phục từ file JSON',
  'restore_cloud': 'Khôi phục toàn bộ từ cloud',
  'export_done': 'Đã lưu: {p}',
  'import_done': 'Nhập: {a} mới, {u} cập nhật, {s} bỏ qua, {i} lỗi',
  'account': 'Tài khoản',
  'sign_in_google': 'Đăng nhập với Google',
  'sign_out': 'Đăng xuất',
  'offline_mode': 'Đang dùng offline',
  'use_offline': 'Dùng offline, không đăng nhập',
  'login_subtitle':
      'Quản lý chi tiêu thông minh - hoạt động cả khi không có mạng và đồng bộ giữa điện thoại, máy tính.',
  'cloud_not_configured':
      'Chưa kết nối máy chủ đồng bộ. Ứng dụng đang chạy offline — bấm Máy chủ đồng bộ để kết nối.',
  'signing_in': 'Đang mở trình duyệt để đăng nhập...',
  'sign_out_pending':
      'Còn {n} thay đổi chưa đồng bộ. Dữ liệu vẫn được giữ trên máy và sẽ đồng bộ khi bạn đăng nhập lại.',
  'error_validation': 'Dữ liệu chưa hợp lệ, vui lòng kiểm tra lại.',
  'error_auth': 'Phiên đăng nhập hết hạn hoặc bị từ chối. Vui lòng đăng nhập lại.',
  'error_network': 'Không có kết nối mạng. Dữ liệu đã được lưu trên máy.',
  'error_database': 'Lỗi cơ sở dữ liệu. Vui lòng thử lại.',
  'error_storage': 'Không thể xử lý ảnh/tệp. Sẽ tự thử lại sau.',
  'error_sync': 'Đồng bộ chưa hoàn tất, sẽ tự thử lại.',
  'error_provider': 'Dịch vụ bên ngoài đang lỗi.',
  'error_unexpected': 'Đã xảy ra lỗi không mong muốn.',
  'version': 'Phiên bản {v}',
  'today': 'Hôm nay',
  'yesterday': 'Hôm qua',
  'this_month': 'Tháng này',
  'type': 'Loại',
  'bank_title': 'Ghi tự động từ thông báo ngân hàng',
  'bank_subtitle':
      'Tự nhận biến động số dư của mọi ngân hàng và ví, đọc to số tiền và lưu giao dịch.',
  'bank_android_only': 'Tính năng này chỉ có trên điện thoại Android.',
  'bank_permission_ok': 'Đã cấp quyền đọc thông báo',
  'bank_permission_missing': 'Chưa cấp quyền đọc thông báo',
  'bank_grant': 'Cấp quyền',
  'bank_restricted_hint':
      'Nếu công tắc trong Cài đặt bị mờ (Android 13+ khi cài APK ngoài CH Play): mở Thông tin ứng dụng → ⋮ → "Cho phép cài đặt bị hạn chế", rồi cấp quyền lại.',
  'bank_app_info': 'Thông tin ứng dụng',
  'bank_enable': 'Bật ghi tự động',
  'bank_speak': 'Đọc to khi có biến động',
  'bank_speak_expense': 'Đọc cả khoản chi',
  'bank_locate': 'Gắn vị trí cho giao dịch tự động',
  'bank_locate_sub': 'Nhận thông báo là lấy luôn địa chỉ hiện tại',
  'bank_locate_need_always':
      'Để lấy được vị trí cả khi app đang đóng, vào Cài đặt → Quyền → Vị trí và chọn "Luôn cho phép". Nếu không, app chỉ gắn vị trí khi đang mở.',
  'open_settings': 'Mở cài đặt',
  'bank_speak_test': 'Nghe thử giọng đọc',
  'bank_speak_sample': 'Đã nhận năm trăm nghìn đồng, Vietcombank',
  'bank_battery': 'Cho phép chạy nền',
  'bank_battery_hint':
      'Một số máy (Xiaomi, Oppo, Vivo, Samsung) tự tắt ứng dụng chạy nền. Hãy tắt tối ưu pin cho Smart Finance để không bỏ lỡ thông báo.',
  'bank_test_title': 'Thử nhận diện',
  'bank_test_sender': 'Tiêu đề / người gửi',
  'bank_test_content': 'Dán nội dung thông báo',
  'bank_test_run': 'Kiểm tra',
  'bank_test_ok': 'Nhận diện được',
  'bank_test_no': 'Bỏ qua: {reason}',
  'bank_balance': 'Số dư: {n}',
  'bank_supported': 'Ngân hàng & ví nhận diện sẵn',
  'bank_supported_more':
      'Các ngân hàng khác vẫn được nhận diện tự động theo tên ngân hàng và nội dung thông báo.',
  'bank_log': 'Nhật ký thông báo gần đây',
  'bank_log_empty': 'Chưa có thông báo nào liên quan đến tiền.',
  'bank_log_clear': 'Xóa nhật ký',
  'bank_trust_app': 'Tin cậy ứng dụng này',
  'bank_block_app': 'Chặn ứng dụng này',
  'bank_trusted_apps': 'Ứng dụng tin cậy',
  'bank_blocked_apps': 'Ứng dụng bị chặn',
  'bank_ignored': 'Bỏ qua',
  'bank_income_name': 'Nhận tiền',
  'bank_expense_name': 'Chi tiêu',
  'bank_auto_note': 'Tự động từ thông báo {bank}',
  'bank_imported': 'Đã ghi {n} giao dịch từ thông báo ngân hàng',
  'bank_privacy':
      'Nội dung thông báo chỉ được xử lý trên máy. Ứng dụng chỉ đọc thông báo từ ngân hàng và ví; tin nhắn Zalo, Messenger, mạng xã hội, mua sắm, OTP và quảng cáo luôn bị bỏ qua.',
  'bank_pending': '{n} giao dịch đang chờ lưu',
  'bank_reason_ok': 'Hợp lệ',
  'bank_reason_duplicate': 'Trùng thông báo trước',
  'bank_reason_otp': 'Mã OTP',
  'bank_reason_promotion': 'Khuyến mãi / quảng cáo',
  'bank_reason_failed': 'Giao dịch không thành công',
  'bank_reason_reminder': 'Nhắc nợ / sao kê',
  'bank_reason_security': 'Bảo mật / đăng nhập',
  'bank_reason_internal_transfer': 'Nạp/rút ví nội bộ',
  'bank_reason_unknown_app': 'Không phải ứng dụng ngân hàng',
  'bank_reason_sms_not_bank': 'SMS không phải từ ngân hàng',
  'bank_reason_weak_signature': 'Không đủ dấu hiệu giao dịch',
  'bank_reason_no_amount': 'Không thấy số tiền',
  'bank_reason_balance_only': 'Chỉ có số dư',
  'bank_reason_unknown_direction': 'Không rõ tiền vào hay ra',
  'bank_reason_user_blocked': 'Bạn đã chặn ứng dụng này',
  'bank_reason_blocked_app': 'Ứng dụng chat / mạng xã hội',
  'bank_reason_bad_amount': 'Số tiền không hợp lệ',
  'bank_reason_empty': 'Thông báo trống',
  'glass_blur_all': 'Làm mờ kính cho mọi thẻ (đẹp hơn, tốn pin hơn)',
  'animated_background': 'Nền chuyển động',
  'menu': 'Menu',
  'main_sections': 'Chính',
  'bank_section': 'Ghi tự động',
  'tab_home': 'Trang chủ',
  'greeting': 'Xin chào, {name} 👋',
  'greeting_you': 'Bạn',
  'greeting_sub': 'Quản lý tài chính thông minh mỗi ngày.',
  'menu_features': 'Menu chức năng',
  'new_features': 'Chức năng mới',
  'new_badge': 'MỚI',
  'no_notifications': 'Không có cảnh báo nào. Mọi thứ đều ổn!',
  'total_assets': 'Tổng tài sản',
  'hide_balance': 'Ẩn số dư',
  'show_balance': 'Hiện số dư',
  'today_income': '+{n} hôm nay',
  'income_total': 'Thu nhập',
  'expense_total': 'Chi tiêu',
  'savings': 'Tiết kiệm',
  'home_month': 'Tháng {m}/{y}',
  'monitoring_on': 'Giám sát đang bật',
  'monitoring_off': 'Giám sát đang tắt',
  'monitoring_on_sub': 'Đang tự động đọc số dư giao dịch',
  'monitoring_off_sub': 'Ứng dụng sẽ không đọc khi có tiền về',
  'today_overview': 'Tổng quan hôm nay',
  'tx_count_label': 'Số giao dịch',
  'net_flow': 'Dòng tiền thuần',
  'tx_detail_title': 'Chi tiết giao dịch',
  'delete_tx_confirm': 'Bạn có chắc chắn muốn xóa giao dịch này không?',
  'reset': 'Đặt lại',
  'advanced_filter': 'Bộ lọc nâng cao',
  'search_tx': 'Tìm kiếm giao dịch...',
  'clear': 'Xoá',
  'this_week': 'Tuần này',
  'this_year': 'Năm nay',
  'month_n': 'Tháng {n}',
  'no_tx_yet': 'Chưa có giao dịch nào',
  'no_tx_filter': 'Không có giao dịch phù hợp',
  'no_tx_yet_sub': 'Hãy bắt đầu ghi lại các khoản thu chi của bạn.',
  'specific_time': 'Thời gian cụ thể',
  'pick_day': 'Chọn ngày',
  'pick_month': 'Chọn tháng',
  'pick_year': 'Chọn năm',
  'clear_time_filter': 'Xóa lọc thời gian',
  'amount_range': 'Mức tiền',
  'under_100k': 'Dưới 100k',
  'under_500k': 'Dưới 500k',
  'over_1m': 'Trên 1 triệu',
  'apply_filter': 'Áp dụng bộ lọc',
  'days_n': '{n} ngày',
  'months_n': '{n} tháng',
  'years_n': '{n} năm',
  'no_stats': 'Chưa có dữ liệu thống kê',
  'no_stats_sub': 'Hãy thêm giao dịch để bắt đầu theo dõi tài chính.',
  'cash_flow': 'Dòng tiền',
  'transactions': 'Giao dịch',
  'balance_trend': 'Biến động số dư',
  'need_more_data': 'Cần thêm dữ liệu để hiển thị biểu đồ',
  'income_vs_expense': 'So sánh Thu - Chi',
  'tx_habits': 'Thói quen giao dịch',
  'peak_hour': 'Giờ hoạt động nhiều nhất',
  'peak_day': 'Ngày hoạt động nhiều nhất',
  'avg_per_day': 'Trung bình mỗi ngày',
  'n_tx_short': '{n} GD',
  'income_trend': 'Xu hướng thu nhập',
  'trend_empty': 'Chưa có dữ liệu để phân tích xu hướng.',
  'trend_start': 'Bắt đầu theo dõi thu nhập từ tháng này.',
  'trend_up': 'Thu nhập tháng này tăng {p}% so với tháng trước. Tuyệt vời!',
  'trend_down': 'Thu nhập tháng này giảm {p}% so với tháng trước. Hãy cố gắng hơn nhé!',
  'trend_flat': 'Thu nhập của bạn đang ổn định so với tháng trước.',
  'user_default': 'Người dùng Smart Finance',
  'not_connected_google': 'Chưa đăng nhập',
  'services_permissions': 'Dịch vụ & Quyền hạn',
  'autostart': 'Tự khởi động',
  'restart_listener': 'Khởi động lại dịch vụ thông báo',
  'restart_listener_done': 'Đã khởi động lại dịch vụ đọc thông báo',
  'tts_settings': 'Cài đặt giọng đọc hệ thống',
  'granted_permissions': 'Các quyền đã được cấp',
  'perm_notification': 'Quyền truy cập thông báo',
  'perm_battery': 'Bỏ qua tối ưu hoá pin',
  'granted': 'Đã cấp',
  'not_granted': 'Chưa cấp',
  'sound': 'Âm thanh',
  'volume_boost': 'Khuếch đại âm thanh',
  'volume_boost_sub': 'Tăng cường âm lượng cho môi trường ồn',
  'voice': 'Giọng đọc',
  'voice_female': 'Nữ',
  'voice_male': 'Nam',
  'chime': 'Âm báo',
  'chime_default': 'Mặc định',
  'chime_ting': 'Ting Ting',
  'chime_none': 'Tắt',
  'speech_rate': 'Tốc độ đọc: {p}%',
  'speech_pitch': 'Cao độ: {p}%',
  'data_backup': 'Dữ liệu & Sao lưu',
  'auto_backup': 'Tự động sao lưu (đồng bộ đám mây)',
  'login_for_backup': 'Đăng nhập (email hoặc Google) để bật sao lưu đám mây.',
  'simulate': 'Giả lập',
  'simulate_title': 'Giả lập giao dịch',
  'simulate_content': 'Nội dung tin nhắn',
  'simulate_run': 'Chạy giả lập',
  'simulate_sample':
      'TK 1012345678 +150,000VND vao 12:30. SD 1,250,000VND. ND: Chuyen khoan tu NGUYEN VAN A',
  'delete_all': 'Xóa hết',
  'delete_all_confirm':
      'Toàn bộ dữ liệu giao dịch sẽ bị xóa vĩnh viễn (cả trên đám mây). Bạn có chắc chắn không?',
  'deleted_n': 'Đã xoá {n} giao dịch',
  'developer': 'Nhà phát triển: Uri Shaw',
  'about_desc':
      'Được phát triển với mục tiêu mang lại trải nghiệm đọc thông báo thông minh, vui nhộn và thân thiện.',
  'sign_out_confirm': 'Bạn có chắc chắn muốn đăng xuất không?',
};
